### PR TITLE
Rewrite HDI function

### PR DESCRIPTION
**Pull request by dsfulf**
I believe this HDI function performs the same as the one that was written, as best I understood what it was doing. It should run much faster as it evaluates all dates simultaneously using a more functional approach.

### CODE REVIEW

**Comment by k-sys** [comment]
Unfortunately this chooses the equal-tailed interval. And HDI chooses the maximum density region where the probability = X. You have to iterate through all possible intervals where the probability = X and choose the one which spans the least distance (eg. highest density). It's often confused with the equal-tailed interval but is different.

**Comment by dsfulf** [comment]
Got it. I've updated it to just wrap your code in a `numba` `jit`, which is going to be faster than any functional approach with `numpy`, I think. I get ~29s to compute HDIs for all states.

Removing the `pd.Series` constructor saves a lot of cycles as well.

**Comment by dsfulf** [comment]
added @kpelechrinis contribution of a map tiled plot

**Comment by k-sys** [comment]
Thank you - I have a vectorized solution that I believe will work well, but I haven't had a chance to confirm yet on the new data. You're right that this is incredibly slow... will take a look at this asap

**Comment by kpelechrinis** [comment]
I think that the following implementation is much faster and provides the same results (based on limited tests). 

```
from bisect import bisect

def highest_density_interval(pmf, p=.95):
    
    # If we pass a DataFrame, just call this recursively on the columns
    if(isinstance(pmf, pd.DataFrame)):
        return pd.DataFrame([highest_density_interval(pmf[col]) for col in pmf],
                            index=pmf.columns)
    
    cumsum = np.cumsum(pmf.values)
    best = None
    for i, value in enumerate(cumsum):
        if value <= 1-p:
            upper = bisect(cumsum,value+p)
            if not best or upper-i < best[1]-best[0]:
                best = (i,upper)
            
    low = pmf.index[best[0]]
    high = pmf.index[best[1]]
    return pd.Series([low, high], index=['Low', 'High'])
```

Let me know your thoughts. I will do more tests too

**Comment by dsfulf** [comment]
@kpelechrinis This is still going to perform poorly because of the call to `pd.Series` for each date. The version I posted is a vectorized computation and uses numba to JIT compile the function to C, which is going to be about as fast as one can get with any approach that doesn’t have an implementation to converge on the HDI rather than test every value.

**Comment by kpelechrinis** [comment]
The implementation I have does not go over all possible values but rather uses properties of CDF and of the HDI. Just tried and takes about ~12 seconds to compute HDIs of all 50 states.

**Comment by dsfulf** [comment]
I see, it's a significant improvement! However, the bisect still goes over every value in its implementation.

I moved the `@jit` out from closing over the function definition, as it seemed to recompile each loop, and altered the search direction depending on the value of p.

 Here are my `%timeit` results:

- Using the `bisect` method:
`37.4 ms ± 1.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)`

- Using the jitted function:
`10.6 ms ± 372 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`

``` python
@jit
def find_best(cdf, p):
    n = len(cdf)
    best = (0, n-1)
    for i in range(n):
        if cdf[i] > 1.0 - p:
            break
        for j in range(n-1, i+1, -1):
            if cdf[j] - cdf[i] < p:
                break
            if j - i < best[1] - best[0]:
                best = (i, j)
    return best


def highest_density_interval(pmf: Union[pd.DataFrame, pd.Series], p=.9):
    index = pmf.index.values
    cdf = np.cumsum(pmf.values, axis=0)
    best = np.atleast_2d(np.apply_along_axis(lambda c: find_best(c, p), axis=0, arr=cdf).T)
    interval = [(index[l], index[h]) for l, h in best]

    return pd.DataFrame(interval,
                        index=(pmf.columns if isinstance(pmf, pd.DataFrame) else [1]),
                        columns=[f'Low_{p*100:.0f}', f'High_{p*100:.0f}'])
```

**Comment by k-sys** [comment]
Just merged Adam Lerer's solution which is v quick. Closing for now thank you for the help!

**Comment by dsfulf** [comment]
It's actually pretty slow. Here's the timing for it.

`577 ms ± 9.01 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

**Pull request closed without merging**
